### PR TITLE
Fixed #17  check for duplicate lines

### LINKED ISSUE #17: J1939 make Write Lines and Replace Line check for duplicate names
check for duplicate names see Issue#77 and Issue#78

### PR DESCRIPTION
**Pull request by jacobson3**
error from disconnect channel is now ignored so module will not error out when trying to disconnect a channel that doesn't currently have a mapping.

Edited "Replace Line.vi" to check for duplicate lines before replacing input line, similar to the most up to date project template.

### CODE REVIEW

**Comment by pollockm** [comment]
@jacobson3  - what's the reason for re-writing the FindDuplicate.vi found here: <vi.lib>\NI\Tag Bus Module Framework\module configuration\FindDuplicate.vi  ?

**Comment by jacobson3** [comment]
I didn't know that VI existed. I'll replace my code with that VI.

**Comment by jacobson3** [comment]
@pollockm Not sure exactly what is failing with the auto tests. I can run the "run-utf.vi" step from the command line using the same labview-cli calls and it works locally on my test computer but Jenkins is reporting the following error.

Error receiving header: Header bytes missing, received 0 of 4 bytes

**Comment by jacobson3** [comment]
@becega 
Will you have any time to review this in the next week or so? If not let me know and I can flag someone else for review.

**Review by becega — APPROVED** [review]
Looks Good

**Pull request merged**
